# Generated by Django 4.1.7 on 2023-04-01 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message", old_name="content", new_name="context",
        ),
    ]
